### ISSUE TITLE
Support handling 404s when a resource has been deleted

### ISSUE THREAD

**Issue by maristgeek** [logdna/terraform-provider-logdna#54] opened 2022-06-29 16:14 UTC
We've had several instances of a human user deleting views that are managed by terraform, which the provider does not handle well.

```hcl
Error: Cannot read the remote view resource

  with module.logdna-views-prod.logdna_view.errors_in_satellite,
  on ../../modules/logdna_prod/main.tf line 822, in resource "logdna_view" "errors_in_satellite":
 822: resource "logdna_view" "errors_in_satellite" {

GET https://REDACTED_HOSTNAME/v1/config/view/REDACTED_ID, status 404 NOT OK! {"error":"Resource Not Found","code":"NotFound","status":"error"}
```

Typically providers see this as needing to recreate the resource.

**Comment by gjanco** [comment] 2022-08-29 14:37
Will be tracked by #53

**Comment by gjanco** [comment] 2022-08-29 14:38
Duplicate of #53

**Closed by gjanco** 2022-08-29 14:38 UTC
